ALTER TABLE dbo.OrderItem
DROP CONSTRAINT FK_OrderId;

ALTER TABLE dbo.OrderItem
DROP CONSTRAINT PK__OrderIte__57ED0681CD94A2CD;

ALTER TABLE dbo.[Order]
DROP CONSTRAINT FK_CustomerId;

ALTER TABLE dbo.[Order]
DROP CONSTRAINT PK__Order__C3905BCF3A17929E;

ALTER TABLE dbo.Customer
DROP CONSTRAINT PK__Customer__A4AE64D881A0177F;

ALTER TABLE dbo.Customer
DROP COLUMN CustomerId;

ALTER TABLE dbo.[Order]
DROP COLUMN OrderId;

ALTER TABLE dbo.OrderItem
DROP COLUMN OrderItemId;

ALTER TABLE dbo.Customer
   ADD CustomerId INT IDENTITY(1,1)
       CONSTRAINT PK_Customer PRIMARY KEY CLUSTERED;

ALTER TABLE dbo.[Order]
   ADD OrderId INT IDENTITY(1,1)
       CONSTRAINT PK_Order PRIMARY KEY CLUSTERED;

ALTER TABLE dbo.[Order]
ADD CONSTRAINT FK_Customer
FOREIGN KEY (CustomerId) REFERENCES Customer(CustomerId);

ALTER TABLE dbo.OrderItem
   ADD OrderItemId INT IDENTITY(1,1)
       CONSTRAINT PK_OrderItem PRIMARY KEY CLUSTERED;

ALTER TABLE dbo.OrderItem
ADD CONSTRAINT FK_Order
FOREIGN KEY (OrderId) REFERENCES [Order](OrderId);